### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by shadowzlh** [Ymjie/QluBookLib#2]
请问一下, 验证码是怎么解决的, 不太熟悉 go , 看了看代码,没有找到相关的地方

**Comment by Ymjie** [comment]
手机端接口，不需要验证码
[Login方法](https://github.com/Ymjie/QluBookLib/blob/main/internal/lib/lib.go#L47)

**Comment by shadowzlh** [comment]
懂了, 谢谢啊 ,我也写了一个, 但是需要验证码, 所以有点好奇
